import type { UIBlock } from "./ui";

// Attachments come in two shapes that share ``kind``/``name``/``media_type``
// but differ in where the bytes live:
//
// 1. **Inline** — the payload is carried on the message itself via ``data``
//    (base64 for images/documents) or ``text`` (decoded UTF-8 for text).
//    This is how user uploads from the chat input arrive: the frontend
//    base64-encodes the file, the server validates, and the blob rides
//    through storage as part of the message row.
//
// 2. **Workspace reference** — ``workspace_skill`` + ``workspace_path``
//    name a file already on disk under the user's skill workspace. No
//    bytes are carried on the message; the frontend calls
//    ``skills.workspace.download`` when the user clicks download. This is
//    how assistant attachments (PDFs/images generated by a tool script)
//    arrive — we keep the binary out of the conversation row so chat
//    history stays small.
//
// Both modes can appear on either user or assistant messages, though in
// practice user messages are always inline and assistant messages are
// almost always references.
export interface FileAttachmentBase {
  kind: "image" | "document" | "text";
  name?: string;
  media_type: string;
  /** Inline base64 payload (images/documents). */
  data?: string;
  /** Inline UTF-8 payload (text attachments). */
  text?: string;
  /** Workspace reference: which skill's workspace the file lives in. */
  workspace_skill?: string;
  /** Workspace reference: file path within that workspace. */
  workspace_path?: string;
  /** Workspace reference: conversation id whose per-conv workspace
   *  holds the file. Empty for legacy attachments persisted before
   *  per-conversation workspaces — those resolve via the legacy
   *  per-(user, skill) path on the backend. */
  workspace_conv?: string;
}

export type FileAttachment = FileAttachmentBase;

export function isReferenceAttachment(
  att: FileAttachment,
): att is FileAttachmentBase & { workspace_skill: string; workspace_path: string } {
  return !!att.workspace_path && !!att.workspace_skill;
}

export interface ConversationSummary {
  conversation_id: string;
  title: string;
  preview: string;
  updated_at: string;
  message_count: number;
  shared: boolean;
  member_count?: number;
  members?: ConversationMember[];
  visibility?: "public" | "invite";
  is_member?: boolean;
  is_invited?: boolean;
}

export interface ConversationMember {
  user_id: string;
  display_name: string;
  role?: "owner" | "member";
}

export interface ConversationDetail {
  conversation_id: string;
  title: string;
  /** Turn-grouped history. Each turn is one user→assistant exchange
   *  with intermediate rounds + final answer. Replaces the old
   *  ``messages`` field. */
  turns: ChatTurn[];
  ui_blocks: UIBlock[];
  updated_at: string;
  shared: boolean;
  members?: ConversationMember[];
  invites?: { user_id: string; display_name: string }[];
  owner_id?: string;
}

export interface ToolUsageEntry {
  tool_name: string;
  is_error: boolean;
  arguments?: Record<string, unknown>;
  result?: string;
  /** The assistant's reasoning preamble from the round that dispatched
   *  this tool — e.g. "Let me check the skill workspace first..." that
   *  the AI said alongside the tool_use block. Rendered in the
   *  "tools used" panel so the reasoning stays visible across the turn,
   *  not just during the brief streaming window before the next round. */
  reasoning?: string;
}

export interface ChatResponse {
  response: string;
  conversation_id: string;
  ui_blocks: UIBlock[];
  tool_usage?: ToolUsageEntry[];
  attachments?: FileAttachment[];
  /** Per-round breakdown of intermediate AI reasoning + tool calls.
   *  The frontend uses this as the authoritative committed shape for
   *  the just-finished turn, replacing whatever live state the
   *  streaming buffer accumulated during the RPC. */
  rounds?: ChatRound[];
  /** True when the turn was interrupted mid-flight by the user via
   *  ``chat.message.cancel``. Partial state (completed rounds, any
   *  attachments produced before the stop) is preserved in the
   *  response; the frontend renders a subtle stop indicator. */
  interrupted?: boolean;
}

// ── Turn-grouped chat history ────────────────────────────────────────
//
// A "turn" is one user → assistant exchange. The user side is a single
// message; the assistant side is one or more agentic ``rounds`` (each
// round being a chunk of reasoning text followed by some tool calls)
// plus a ``final`` answer carrying the user-visible reply text and any
// downloadable attachments.
//
// This shape is what ``chat.history.load.result`` returns and what
// ``chat.message.send.result`` includes alongside the legacy fields. The
// frontend renders one ``TurnBubble`` per ``ChatTurn``.
export interface ChatRoundTool {
  tool_call_id: string;
  tool_name: string;
  arguments?: Record<string, unknown>;
  result?: string;
  is_error?: boolean;
  /** "running" only used during live streaming; persisted history
   *  entries are always "done". */
  status?: "running" | "done";
}

export interface ChatRound {
  reasoning: string;
  tools: ChatRoundTool[];
}

export interface ChatTurnUserMessage {
  content: string;
  attachments: FileAttachment[];
  author_id?: string;
  author_name?: string;
}

export interface ChatTurn {
  user_message: ChatTurnUserMessage;
  rounds: ChatRound[];
  final_content: string;
  final_attachments: FileAttachment[];
  final_author_id?: string;
  final_author_name?: string;
  /** True if the turn never produced a final assistant message — the
   *  agentic loop hit max_tool_rounds or the AI errored. Interrupted
   *  turns use the ``interrupted`` flag instead; this one is for
   *  unintentional incompletion. */
  incomplete: boolean;
  /** True when the user stopped the turn mid-flight via the stop
   *  button (chat.message.cancel RPC). Partial state (completed
   *  rounds, tool calls so far) is preserved; the TurnBubble renders
   *  a subtle stop icon to make it clear the turn didn't finish
   *  organically. Distinct from ``incomplete`` which covers unintended
   *  cutoffs. */
  interrupted?: boolean;
  /** True while the turn is being built from streaming events. The
   *  current round's reasoning pulses; previous rounds and the final
   *  answer (if any yet) are static. Cleared once the
   *  ``chat.message.send`` RPC resolves and the turn is committed. */
  streaming?: boolean;
}
