"""Greeting service — personalized arrival greetings via presence events.

Listens for ``presence.arrived`` events and announces a unique greeting
over speakers using TTS. Tracks who has been greeted today to avoid
repeats. Greeting text is generated by the AI service.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from gilbert.interfaces.events import Event, EventBus
from gilbert.interfaces.service import Service, ServiceInfo, ServiceResolver
from gilbert.interfaces.tools import (
    ToolDefinition,
    ToolParameter,
    ToolParameterType,
)

logger = logging.getLogger(__name__)

_GREETING_COLLECTION = "greeting_state"


class GreetingService(Service):
    """Personalized arrival greetings driven by presence events.

    Capabilities: greeting
    """

    def __init__(self) -> None:
        self._event_bus: EventBus | None = None
        self._storage_backend: Any = None  # StorageBackend
        self._ai: Any = None  # AIService
        self._speaker: Any = None  # SpeakerService
        self._resolver: ServiceResolver | None = None
        self._unsubscribe: Any = None

        # Config
        self._start_hour: int = 6
        self._cutoff_hour: int = 14
        self._style: str = ""
        self._speakers: list[str] = []
        self._voice_name: str = ""
        self._timezone: str = "UTC"

    def service_info(self) -> ServiceInfo:
        return ServiceInfo(
            name="greeting",
            capabilities=frozenset({"greeting", "ai_tools"}),
            requires=frozenset({"event_bus", "entity_storage"}),
            optional=frozenset({"ai", "speaker_control", "text_to_speech", "presence", "configuration"}),
        )

    async def start(self, resolver: ServiceResolver) -> None:
        self._resolver = resolver

        # Get event bus and subscribe
        event_bus_svc = resolver.require_capability("event_bus")
        self._event_bus = event_bus_svc.bus
        self._unsubscribe = self._event_bus.subscribe("presence.arrived", self._on_arrival)

        # Entity storage for dedup tracking
        storage_svc = resolver.require_capability("entity_storage")
        self._storage_backend = getattr(storage_svc, "backend", storage_svc)

        # Load config
        config_svc = resolver.get_capability("configuration")
        if config_svc is not None:
            from gilbert.core.services.configuration import ConfigurationService

            if isinstance(config_svc, ConfigurationService):
                section = config_svc.get_section("greeting")
                self._start_hour = int(section.get("start_hour", 6))
                self._cutoff_hour = int(section.get("cutoff_hour", 14))
                self._style = section.get("style", "")
                self._speakers = section.get("speakers", [])
                self._voice_name = section.get("voice_name", "")

                # Get timezone from app config
                app_section = config_svc.get_section("presence")
                self._timezone = app_section.get("timezone", "UTC")

        logger.info(
            "Greeting service started (window=%d:00-%d:00)",
            self._start_hour, self._cutoff_hour,
        )

    async def stop(self) -> None:
        if self._unsubscribe:
            self._unsubscribe()

    async def _on_arrival(self, event: Event) -> None:
        """Handle a presence.arrived event."""
        user_id = event.data.get("user_id", "")
        if not user_id:
            return

        # Check time window
        if not self._in_greeting_window():
            return

        # Check if already greeted today
        if await self._has_been_greeted_today(user_id):
            return

        # Generate and announce greeting
        display_name = self._get_display_name(user_id)
        greeting = await self._generate_greeting(display_name)

        logger.info("Greeting %s: %s", user_id, greeting)

        # Mark as greeted before announcing (avoid races)
        await self._mark_greeted(user_id)

        # Announce via speakers
        await self._announce(greeting)

        # Publish event
        if self._event_bus:
            await self._event_bus.publish(Event(
                event_type="greeting.announced",
                data={"user_id": user_id, "greeting": greeting},
                source="greeting",
            ))

    def _in_greeting_window(self) -> bool:
        """Check if current time is within the greeting window."""
        try:
            from zoneinfo import ZoneInfo

            now = datetime.now(ZoneInfo(self._timezone))
        except Exception:
            now = datetime.now(timezone.utc)

        return self._start_hour <= now.hour < self._cutoff_hour

    def _get_display_name(self, user_id: str) -> str:
        """Extract a display-friendly name from user_id."""
        # user_id might be an email or a name
        if "@" in user_id:
            # Take the local part and capitalize
            local = user_id.split("@")[0]
            return local.replace(".", " ").replace("_", " ").title()
        return user_id.split()[0] if " " in user_id else user_id

    async def _has_been_greeted_today(self, user_id: str) -> bool:
        """Check if user has been greeted today."""
        if self._storage_backend is None:
            return False

        record = await self._storage_backend.get(_GREETING_COLLECTION, user_id)
        if not record:
            return False

        today = self._today_str()
        return record.get("last_greeting_date") == today

    async def _mark_greeted(self, user_id: str) -> None:
        """Mark user as greeted today."""
        if self._storage_backend is None:
            return

        today = self._today_str()
        record = await self._storage_backend.get(_GREETING_COLLECTION, user_id)
        count = (record.get("greeting_count", 0) if record else 0) + 1

        await self._storage_backend.put(_GREETING_COLLECTION, user_id, {
            "user_id": user_id,
            "last_greeting_date": today,
            "greeting_count": count,
        })

    def _today_str(self) -> str:
        """Get today's date string in the configured timezone."""
        try:
            from zoneinfo import ZoneInfo

            return datetime.now(ZoneInfo(self._timezone)).strftime("%Y-%m-%d")
        except Exception:
            return datetime.now(timezone.utc).strftime("%Y-%m-%d")

    async def _generate_greeting(self, name: str) -> str:
        """Generate a personalized greeting via AI, with fallback."""
        # Resolve AI lazily (it may start after us)
        if self._resolver is None:
            return f"Good morning, {name}!"

        ai_svc = self._resolver.get_capability("ai")
        if ai_svc is None:
            return f"Good morning, {name}!"

        style_instruction = ""
        if self._style:
            style_instruction = f" Style: {self._style}."

        prompt = (
            f"Generate a unique, fun morning greeting for {name} who just arrived. "
            f"You're Gilbert, an AI assistant. Be playful, creative, and different "
            f"every time. Mention their name. Keep it to 1-2 sentences. "
            f"Write ONLY the greeting text — no quotes, no preamble.{style_instruction}"
        )

        try:
            from gilbert.interfaces.auth import UserContext

            response, _ = await ai_svc.chat(
                prompt,
                user_ctx=UserContext.SYSTEM,
            )
            if response and len(response) < 500:
                return response.strip()
        except Exception:
            logger.warning("AI greeting generation failed", exc_info=True)

        return f"Good morning, {name}!"

    # ── ToolProvider Protocol ───────────────────────────────────

    @property
    def tool_provider_name(self) -> str:
        return "greeting"

    def get_tools(self) -> list[ToolDefinition]:
        return [
            ToolDefinition(
                name="greet",
                description=(
                    "Generate and announce a personalized greeting for someone. "
                    "Use this when a user asks you to greet someone or welcome them."
                ),
                parameters=[
                    ToolParameter(
                        name="name",
                        type=ToolParameterType.STRING,
                        description="Name of the person to greet.",
                    ),
                ],
                required_role="user",
            ),
        ]

    async def execute_tool(self, name: str, arguments: dict[str, Any]) -> str:
        if name != "greet":
            raise KeyError(f"Unknown tool: {name}")

        person_name = arguments.get("name", "").strip()
        if not person_name:
            return "I need a name to greet."

        greeting = await self._generate_greeting(person_name)
        await self._announce(greeting)

        return f'Greeted {person_name}: "{greeting}"'

    # ── Announce ────────────────────────────────────────────────

    async def _announce(self, text: str) -> None:
        """Announce greeting via speakers."""
        if self._resolver is None:
            return

        speaker_svc = self._resolver.get_capability("speaker_control")
        if speaker_svc is None:
            logger.debug("No speaker service — greeting not announced: %s", text)
            return

        try:
            await speaker_svc.announce(
                text,
                speaker_names=self._speakers or None,
                voice_name=self._voice_name or None,
            )
        except Exception:
            logger.warning("Failed to announce greeting", exc_info=True)
