"""Greeting service — personalized arrival greetings via presence events.

Listens for ``presence.arrived`` events and announces a unique greeting
over speakers using TTS. Tracks who has been greeted today to avoid
repeats. Greeting text is generated by the AI service.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from gilbert.interfaces.configuration import ConfigParam
from gilbert.interfaces.events import Event, EventBus
from gilbert.interfaces.service import Service, ServiceInfo, ServiceResolver
from gilbert.interfaces.storage import StorageProvider
from gilbert.interfaces.tools import (
    ToolDefinition,
    ToolParameter,
    ToolParameterType,
)

logger = logging.getLogger(__name__)

_GREETING_COLLECTION = "greeting_state"


class GreetingService(Service):
    """Personalized arrival greetings driven by presence events.

    Capabilities: greeting
    """

    def __init__(self) -> None:
        self._enabled: bool = False
        self._event_bus: EventBus | None = None
        self._storage_backend: Any = None  # StorageBackend
        self._ai: Any = None  # AIService
        self._speaker: Any = None  # SpeakerService
        self._resolver: ServiceResolver | None = None
        self._unsubscribe: Any = None

        # Config
        self._start_hour: int = 6
        self._cutoff_hour: int = 14
        self._style: str = ""
        self._speakers: list[str] = []
        self._timezone: str = "UTC"

    def service_info(self) -> ServiceInfo:
        return ServiceInfo(
            name="greeting",
            capabilities=frozenset({"greeting", "ai_tools"}),
            requires=frozenset({"event_bus", "entity_storage"}),
            optional=frozenset({"ai", "speaker_control", "text_to_speech", "presence", "configuration"}),
            ai_calls=frozenset({"greeting"}),
            events=frozenset({"greeting.announced"}),
            toggleable=True,
            toggle_description="Automated greeting announcements",
        )

    async def start(self, resolver: ServiceResolver) -> None:
        self._resolver = resolver

        # Check enabled
        config_svc = resolver.get_capability("configuration")
        if config_svc is not None:
            from gilbert.interfaces.configuration import ConfigurationReader

            if isinstance(config_svc, ConfigurationReader):
                section = config_svc.get_section(self.config_namespace)
                if not section.get("enabled", False):
                    logger.info("Greeting service disabled")
                    return

        self._enabled = True

        # Get event bus and subscribe
        event_bus_svc = resolver.require_capability("event_bus")
        self._event_bus = event_bus_svc.bus
        self._unsubscribe = self._event_bus.subscribe("presence.arrived", self._on_arrival)

        # Entity storage for dedup tracking
        storage_svc = resolver.require_capability("entity_storage")
        if isinstance(storage_svc, StorageProvider):
            self._storage_backend = storage_svc.backend

        # Load config
        if config_svc is not None:
            from gilbert.interfaces.configuration import ConfigurationReader

            if isinstance(config_svc, ConfigurationReader):
                section = config_svc.get_section(self.config_namespace)
                self._start_hour = int(section.get("start_hour", 6))
                self._cutoff_hour = int(section.get("cutoff_hour", 14))
                self._style = section.get("style", "")
                self._speakers = section.get("speakers", [])
                self._timezone = section.get("timezone", "UTC")

        # Schedule a one-shot check for people already present at startup.
        # This handles the case where Gilbert restarts while people are
        # already at the shop — they won't get a presence.arrived event
        # because the presence service suppresses events for users seen
        # on the first poll.
        scheduler = resolver.get_capability("scheduler")
        if scheduler is not None:
            from gilbert.interfaces.scheduler import Schedule, SchedulerProvider

            if isinstance(scheduler, SchedulerProvider):
                scheduler.add_job(
                    name="greeting-startup-check",
                    schedule=Schedule.once_after(45),
                    callback=self._greet_already_present,
                    system=True,
                )

        logger.info(
            "Greeting service started (window=%d:00-%d:00)",
            self._start_hour, self._cutoff_hour,
        )

    async def stop(self) -> None:
        if self._unsubscribe:
            self._unsubscribe()

    # --- Configurable protocol ---

    @property
    def config_namespace(self) -> str:
        return "greeting"

    @property
    def config_category(self) -> str:
        return "Communication"

    def config_params(self) -> list[ConfigParam]:
        return [
            ConfigParam(
                key="start_hour", type=ToolParameterType.INTEGER,
                description="Hour of day to start greeting (0-23).",
                default=6,
            ),
            ConfigParam(
                key="cutoff_hour", type=ToolParameterType.INTEGER,
                description="Hour of day to stop greeting (0-23).",
                default=14,
            ),
            ConfigParam(
                key="timezone", type=ToolParameterType.STRING,
                description="Timezone for greeting window.",
                default="UTC",
            ),
            ConfigParam(
                key="style", type=ToolParameterType.STRING,
                description="Custom style instructions for AI greeting generation.",
                default="",
                multiline=True,
            ),
            ConfigParam(
                key="speakers", type=ToolParameterType.ARRAY,
                description="Speaker names for announcements (empty = all).",
                default=[],
                choices_from="speakers",
            ),
        ]

    async def on_config_changed(self, config: dict[str, Any]) -> None:
        self._start_hour = int(config.get("start_hour", self._start_hour))
        self._cutoff_hour = int(config.get("cutoff_hour", self._cutoff_hour))
        self._style = config.get("style", self._style)
        self._speakers = config.get("speakers", self._speakers)
        self._timezone = config.get("timezone", self._timezone)

    async def _greet_already_present(self) -> None:
        """Greet anyone already present at startup who hasn't been greeted today.

        Instead of greeting each person individually (which would cause
        announcements to step on each other), generates a single combined
        greeting for everyone present.
        """
        if not self._in_greeting_window():
            logger.info("Startup greeting skipped — outside greeting window")
            return

        presence_svc = self._resolver.get_capability("presence") if self._resolver else None
        if presence_svc is None:
            logger.info("Startup greeting skipped — no presence service")
            return

        try:
            here = await presence_svc.who_is_here()
        except Exception:
            logger.warning("Startup greeting: could not check who is here", exc_info=True)
            return

        # Filter to people not yet greeted today
        to_greet: list[str] = []
        for p in here:
            if not await self._has_been_greeted_today(p.user_id):
                name = await self._get_display_name(p.user_id)
                to_greet.append(name)

        logger.info(
            "Startup greeting: %d present, %d to greet",
            len(here), len(to_greet),
        )

        if not to_greet:
            return

        # Collect recent greetings across all users for variety
        all_recent: list[str] = []
        for p in here:
            all_recent.extend(await self._get_recent_greetings(p.user_id))

        # Generate a single combined greeting
        greeting = await self._generate_group_greeting(to_greet, all_recent)
        logger.info("Startup greeting: %s", greeting)

        await self._announce(greeting)

        # Mark all as greeted
        for p in here:
            if not await self._has_been_greeted_today(p.user_id):
                await self._mark_greeted(p.user_id, greeting)

        if self._event_bus:
            await self._event_bus.publish(Event(
                event_type="greeting.announced",
                data={"names": to_greet, "greeting": greeting, "startup": True},
                source="greeting",
            ))

    async def _on_arrival(self, event: Event) -> None:
        """Handle a presence.arrived event."""
        user_id = event.data.get("user_id", "")
        if not user_id:
            return
        if not self._in_greeting_window():
            return
        await self._greet_user(user_id)

    async def _greet_user(self, user_id: str) -> None:
        """Greet a user if they haven't been greeted today."""
        if await self._has_been_greeted_today(user_id):
            return

        display_name = await self._get_display_name(user_id)
        recent = await self._get_recent_greetings(user_id)
        greeting = await self._generate_greeting(display_name, recent)

        logger.info("Greeting %s: %s", user_id, greeting)

        await self._mark_greeted(user_id, greeting)
        await self._announce(greeting)

        if self._event_bus:
            await self._event_bus.publish(Event(
                event_type="greeting.announced",
                data={"user_id": user_id, "greeting": greeting},
                source="greeting",
            ))

    def _in_greeting_window(self) -> bool:
        """Check if current time is within the greeting window."""
        try:
            from zoneinfo import ZoneInfo

            now = datetime.now(ZoneInfo(self._timezone))
        except Exception:
            now = datetime.now(timezone.utc)

        return self._start_hour <= now.hour < self._cutoff_hour

    async def _get_display_name(self, user_id: str) -> str:
        """Resolve a user_id to a display-friendly first name."""
        from gilbert.core.user_utils import resolve_display_name

        return await resolve_display_name(user_id, self._resolver, first_name_only=True)

    async def _has_been_greeted_today(self, user_id: str) -> bool:
        """Check if user has been greeted today."""
        if self._storage_backend is None:
            return False

        record = await self._storage_backend.get(_GREETING_COLLECTION, user_id)
        if not record:
            return False

        today = self._today_str()
        return record.get("last_greeting_date") == today

    async def _mark_greeted(self, user_id: str, greeting: str = "") -> None:
        """Mark user as greeted today and store the greeting text."""
        if self._storage_backend is None:
            return

        today = self._today_str()
        record = await self._storage_backend.get(_GREETING_COLLECTION, user_id)
        count = (record.get("greeting_count", 0) if record else 0) + 1

        # Keep a rolling log of recent greetings so the AI can avoid repeats
        recent: list[str] = (record.get("recent_greetings", []) if record else [])
        if greeting:
            recent.append(greeting)
            recent = recent[-10:]  # keep last 10

        await self._storage_backend.put(_GREETING_COLLECTION, user_id, {
            "user_id": user_id,
            "last_greeting_date": today,
            "greeting_count": count,
            "recent_greetings": recent,
        })

    async def _get_recent_greetings(self, user_id: str) -> list[str]:
        """Get recent greeting texts for a user (for anti-repetition)."""
        if self._storage_backend is None:
            return []
        record = await self._storage_backend.get(_GREETING_COLLECTION, user_id)
        if not record:
            return []
        return record.get("recent_greetings", [])

    def _today_str(self) -> str:
        """Get today's date string in the configured timezone."""
        try:
            from zoneinfo import ZoneInfo

            return datetime.now(ZoneInfo(self._timezone)).strftime("%Y-%m-%d")
        except Exception:
            return datetime.now(timezone.utc).strftime("%Y-%m-%d")

    async def _generate_greeting(self, name: str, recent: list[str] | None = None) -> str:
        """Generate a personalized greeting via AI, with fallback."""
        if self._resolver is None:
            return f"Good morning, {name}!"

        ai_svc = self._resolver.get_capability("ai_chat")
        if ai_svc is None:
            return f"Good morning, {name}!"

        style_instruction = ""
        if self._style:
            style_instruction = f"\nStyle: {self._style}."

        avoid_section = ""
        if recent:
            avoid_section = (
                "\n\nHere are your recent greetings — do NOT repeat or closely "
                "paraphrase any of these. Be completely different in tone, "
                "structure, and word choice:\n"
                + "\n".join(f"- {g}" for g in recent[-7:])
            )

        prompt = (
            f"Generate a morning greeting for {name} who just arrived at the shop. "
            f"You're Gilbert, an AI assistant at a business. Be creative — vary your "
            f"tone across days (witty, warm, dramatic, deadpan, poetic, nerdy, etc.). "
            f"Mention their name. 1-2 sentences max. "
            f"Write ONLY the greeting — no quotes, no preamble."
            f"{style_instruction}{avoid_section}"
        )

        try:
            from gilbert.interfaces.auth import UserContext

            response, _, _ui, _tu = await ai_svc.chat(
                prompt,
                user_ctx=UserContext.SYSTEM,
                ai_call="greeting",
            )
            if response and len(response) < 500:
                return response.strip()
        except Exception:
            logger.warning("AI greeting generation failed", exc_info=True)

        return f"Good morning, {name}!"

    async def _generate_group_greeting(self, names: list[str], recent: list[str] | None = None) -> str:
        """Generate a single greeting for multiple people."""
        if len(names) == 1:
            return await self._generate_greeting(names[0], recent)

        if self._resolver is None:
            return f"Good morning, {', '.join(names)}!"

        ai_svc = self._resolver.get_capability("ai_chat")
        if ai_svc is None:
            return f"Good morning, {', '.join(names)}!"

        style_instruction = ""
        if self._style:
            style_instruction = f"\nStyle: {self._style}."

        avoid_section = ""
        if recent:
            avoid_section = (
                "\n\nHere are recent greetings — do NOT repeat or closely "
                "paraphrase any of these. Be completely different:\n"
                + "\n".join(f"- {g}" for g in recent[-7:])
            )

        names_str = ", ".join(names[:-1]) + f", and {names[-1]}"
        prompt = (
            f"Generate a morning greeting for the crew: {names_str}. "
            f"You're Gilbert, an AI assistant at a business. Greet them as a group "
            f"with personality — vary your tone (witty, warm, dramatic, deadpan, etc.). "
            f"Mention a few names naturally. 2-3 sentences max. "
            f"Write ONLY the greeting."
            f"{style_instruction}{avoid_section}"
        )

        try:
            from gilbert.interfaces.auth import UserContext

            response, _, _ui, _tu = await ai_svc.chat(
                prompt,
                user_ctx=UserContext.SYSTEM,
                ai_call="greeting",
            )
            if response and len(response) < 500:
                return response.strip()
        except Exception:
            logger.warning("AI group greeting failed", exc_info=True)

        return f"Good morning, {names_str}!"

    # ── ToolProvider Protocol ───────────────────────────────────

    @property
    def tool_provider_name(self) -> str:
        return "greeting"

    def get_tools(self) -> list[ToolDefinition]:
        if not self._enabled:
            return []
        return [
            ToolDefinition(
                name="greet",
                slash_command="greet",
                slash_help="Announce a personalized greeting: /greet <name>",
                description=(
                    "Generate and announce a personalized greeting for someone. "
                    "Use this when a user asks you to greet someone or welcome them."
                ),
                parameters=[
                    ToolParameter(
                        name="name",
                        type=ToolParameterType.STRING,
                        description="Name of the person to greet.",
                    ),
                ],
                required_role="user",
            ),
        ]

    async def execute_tool(self, name: str, arguments: dict[str, Any]) -> str:
        if name != "greet":
            raise KeyError(f"Unknown tool: {name}")

        person_name = arguments.get("name", "").strip()
        if not person_name:
            return "I need a name to greet."

        greeting = await self._generate_greeting(person_name)
        await self._announce(greeting)

        return f'Greeted {person_name}: "{greeting}"'

    # ── Announce ────────────────────────────────────────────────

    async def _announce(self, text: str) -> None:
        """Announce greeting via speakers."""
        if self._resolver is None:
            return

        speaker_svc = self._resolver.get_capability("speaker_control")
        if speaker_svc is None:
            logger.debug("No speaker service — greeting not announced: %s", text)
            return

        try:
            await speaker_svc.announce(
                text,
                speaker_names=self._speakers or None,
            )
        except Exception:
            logger.warning("Failed to announce greeting", exc_info=True)
